//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarMission.Client.Common.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarMission.Client.Common.Messages.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given all weapons successfully!.
        /// </summary>
        internal static string MSG_ALLWEAPONS_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_ALLWEAPONS_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WayPoint not found!.
        /// </summary>
        internal static string MSG_BLIPNOTFOUND {
            get {
                return ResourceManager.GetString("MSG_BLIPNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entregue o carro no ~p~endereço~w~ marcado no mapa..
        /// </summary>
        internal static string MSG_CARDELIVERYMISSION_DELIVERYCAR {
            get {
                return ResourceManager.GetString("MSG_CARDELIVERYMISSION_DELIVERYCAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t got the ~r~mission~w~!.
        /// </summary>
        internal static string MSG_CARDELIVERYMISSION_FAILED {
            get {
                return ResourceManager.GetString("MSG_CARDELIVERYMISSION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre no ~y~Carro~w~..
        /// </summary>
        internal static string MSG_CARDELIVERYMISSION_GETCAR {
            get {
                return ResourceManager.GetString("MSG_CARDELIVERYMISSION_GETCAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GodMode Disabled!.
        /// </summary>
        internal static string MSG_GODMODE_DISABLED {
            get {
                return ResourceManager.GetString("MSG_GODMODE_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GodMode Enabled!.
        /// </summary>
        internal static string MSG_GODMODE_ENABLED {
            get {
                return ResourceManager.GetString("MSG_GODMODE_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given {0} successfully!.
        /// </summary>
        internal static string MSG_WEAPON_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_WEAPON_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon not found!.
        /// </summary>
        internal static string MSG_WEAPON_UNSUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_WEAPON_UNSUCCESSFULLY", resourceCulture);
            }
        }
    }
}
